In [14]:
from scipy.stats import chi2, f
import numpy as np

In [148]:
# 1. Question 11(a) page 524

# Ho: Ticket purchased is independent of flight type
# Ha: Ticket purchased is not independent of flight type

observed1 = [29,22,95,121,518,135]
expected1 = [35.59,15.41,150.73,65.27,455.68,197.32]


chisquare1 = sum([(x-y)**2/y for x,y in zip(observed1,expected1)])
print('chi_square1: ',chisquare1)

df1 = (3-1)*(2-1)
print('df1:         ',df1)

pvalue1 = 1-chi2.cdf(chisquare1, df1)
print('pvalue1:     ',pvalue1)

chi_square1:  100.4337771754337
df1:          2
pvalue1:      0.0


In [16]:
# Conclusion: As p-value < .05; Reject Ho. Therefore, ticket purchased is not independent of the flight type

In [17]:
# Question 11(b) page 524 - Discuss any independence that exists between type of ticket and type of flight

In [18]:
# percentage of observed data in each column
observed1_percentage = [4.5,7.9,14.8,43.5,80.7,48.6]

# Conclusion: In international flights, a higher percentage of first-class and business-class tickets is purchased

In [19]:
# 2. Question 23(a) page 535

# Ho: Largest companies differ from thousand companies in performance in shareholder scoreboard
# Ha: Largest companies donot differ from thousand companies in performance in shareholder scoreboard

observed1 = [5,8,15,20,12]
expected1 = [12,12,12,12,12]


chisquare1 = sum([(x-y)**2/y for x,y in zip(observed1,expected1)])
print('chi_square1: ',chisquare1)

df1 = (5-1)
print('df1: ',df1)

pvalue1 = 1-chi2.cdf(chisquare1, df1)
print('pvalue1: ',pvalue1)

chi_square1:  11.5
df1:  4
pvalue1:  0.0214837703764


In [20]:
# Conclusion: As p-value < .05; Reject Ho. 
# Therefore, Largest companies donot differ from thousand companies in performance in shareholder scoreboard

In [152]:
# 3. Question 9 page 561

In [153]:
# Hypothesis test:

# Ho: Temperature level has no effect on mean yield of the process
# Ha: Temperature level has an effect on mean yield of the process



In [154]:
data = np.array([[34,24,36,39,32],[30,31,34,23,27],[23,28,28,30,31]])
data

array([[34, 24, 36, 39, 32],
       [30, 31, 34, 23, 27],
       [23, 28, 28, 30, 31]])

In [155]:
sample_size = [len(x) for x in data]
sample_size

[5, 5, 5]

In [156]:
n = sum(sample_size)
k = len(sample_size)
print (n,k)

15 3


In [157]:
grand_mean = data.mean()
print (grand_mean)

30.0


In [158]:
sample_mean = data.mean(axis = 1)
print(sample_mean)

[ 33.  29.  28.]


In [159]:
s = data.std(axis = 1,ddof = 1)
print(s)

[ 5.65685425  4.18330013  3.082207  ]


In [160]:
zip(sample_size, sample_mean)


In [161]:
SSTR = sum([x*(y-grand_mean)**2 for x,y in zip(sample_size, sample_mean)])
df_tr = k-1
MSTR = SSTR/df_tr
print(SSTR, MSTR)

70.0 35.0


In [162]:
SSE = sum([(x-1)*(y**2) for x,y in zip(sample_size, s)])
df_e = n-k
MSE = SSE/df_e
print(SSE, MSE)

236.0 19.6666666667


In [163]:
SST = (n-1)*data.std(ddof=1)**2
df_t = n-1
print(SST, SSTR+SSE)

306.0 306.0


In [164]:
# ANOVA, f-test
f_stat = MSTR/MSE
crit = f.ppf(.95, dfn = df_tr, dfd = df_e)
p_value = 1 - f.cdf(f_stat, dfn = df_tr, dfd = df_e)
print('critcal value: ',crit)
 
print('\nTreatment:',SSTR,'          ',df_tr,'   ',MSTR,'     ',f_stat,'  ',p_value)
print('Error:  ',' ',SSE,'          ',df_e,'  ',MSE) 
print('Total:  ',' ',SST,' ',df_t)

critcal value:  3.88529383465

Treatment: 70.0            2     35.0       1.77966101695    0.210447348811
Error:     236.0            12    19.6666666667
Total:     306.0   14


In [165]:
# Conclusion: As p-value > .05; We do not Reject Ho. 
# Therefore, Temperature level doesnot have an effect on mean yield of the process

In [166]:
# 4.	Problem 31 of Chapter 13, 13th edition, page 581


In [225]:
data = np.array([[[41,43],[52,44],[50,46]],
                 [[49,51],[50,46],[48,44]]])

grand_mean = data.mean()
A_mean = data.mean(axis=(2,1))
B_mean = data.mean(axis=(2,0))

TR_mean = data.mean(axis=2)


In [226]:
data.mean(axis=2)

array([[ 42.,  48.,  48.],
       [ 50.,  48.,  46.]])

In [227]:
data.mean(axis=(2, 1))

array([ 46.,  48.])

In [228]:
data.mean(axis=(2, 0))

array([ 46.,  48.,  47.])

In [229]:
SST = sum([(x-grand_mean)**2 for x in data.flatten()])

data.flatten()

array([41, 43, 52, 44, 50, 46, 49, 51, 50, 46, 48, 44])

In [230]:
# shape of the numpy array

data.shape

(2, 3, 2)

In [231]:
a = data.shape[0]; b = data.shape[1]; r = data.shape[2]

In [232]:
SSA = b*r*sum([(x-grand_mean)**2 for x in A_mean])

In [233]:
SSB = a*r*sum([(x-grand_mean)**2 for x in B_mean])

In [234]:
# compute SSAB

SSAB = 0
for i in range(a):
    for j in range(b):
        SSAB += (TR_mean[i][j] - A_mean[i] - B_mean[j] + grand_mean)**2
SSAB = r*SSAB

In [235]:
# Compute SSE

SSE = SST - SSA - SSB - SSAB

In [236]:
# degrees of freedom

dfa = data.shape[0] - 1
dfb = data.shape[1] - 1
dfab = dfa * dfb
dfe = data.shape[0] * data.shape[1] * (data.shape[2] - 1)
dft = data.shape[0] * data.shape[1] * data.shape[2] - 1

In [237]:
# Mean Squares

MSA = SSA/dfa
MSB = SSB/dfb
MSAB = SSAB/dfab
MSE = SSE/dfe

In [238]:
# F test statistics

fa = MSA/MSE
fb = MSB/MSE
fab = MSAB/MSE

In [239]:
# P VALUES

pa = 1 - f.cdf(fa, dfn = dfa, dfd = dfe)
pb = 1 - f.cdf(fb, dfn = dfb, dfd = dfe)
pab = 1 - f.cdf(fab, dfn = dfab, dfd = dfe)

In [248]:
print('Factor A','      ', SSA,'  ',dfa,'   ',MSA,'   ',fa,'    ',pa)
print('Factor B','      ', SSB,'   ',dfb,'   ',MSB,'    ',fb,'    ',pb)
print('Interaction','   ', SSAB,'  ',dfab,'   ',MSAB,'   ',fab,'    ',pab)
print('Error','         ', SSE,'  ',dfe,'   ',MSE)
print('Total','         ', SST,' ',dft)

Factor A        12.0    1     12.0     1.2      0.315333596201
Factor B        8.0     2     4.0      0.4      0.686952981885
Interaction     56.0    2     28.0     2.8      0.138382057485
Error           60.0    6     10.0
Total           136.0   11


In [ ]:
# Conclusion:

# With p-value for Factor-A  (0.315333596201) greater than .05, it is not significant
# With p-value for Factor-B  (0.686952981885) greater than .05, it is not significant
# With p-value for Interaction of A and B  ( 0.138382057485) greater than .05, 
# therefore, it is not significant for decreasing wait times

#As method is not a significant factor; either of the methods; Loading and Unloading can be used