In [4]:
from scipy.stats import chi2, f
import numpy as np

In [2]:
# 1. Question 11(a) page 524

# Ho: Ticket purchased is independent of flight type
# Ha: Ticket purchased is not independent of flight type



observed1 = [35,70,85,50,65,80,115,100]
expected1 = [40,60,80,60,60,90,120,90]

chisquare1 = sum([(x-y)**2/y for x,y in zip(observed1,expected1)])
print('chi_square1: ',chisquare1)

df1 = (4-1)*(2-1)
print('df1:         ',df1)

pvalue1 = 1-chi2.cdf(chisquare1, df1)
print('pvalue1:     ',pvalue1)

crit = chi2.ppf(1-0.05, df1) #added
print('crit val: ', crit)

chi_square1:  7.118055555555557
df1:          3
pvalue1:      0.0682286310483
crit val:  7.81472790325


In [16]:
# Conclusion: As p-value < .05; Reject Ho. Therefore, ticket purchased is not independent of the flight type
#also chisq>crit so reject h0

In [17]:
# Question 11(b) page 524 - Discuss any dependence that exists between type of ticket and type of flight

In [18]:
# percentage of observed data in each column
observed1_percentage = [4.5,7.9,14.8,43.5,80.7,48.6]

# Conclusion: In international flights, a higher percentage of first-class and business-class tickets is purchased

In [3]:
# 2. Question 23(a) page 535

# Ho: Largest companies differ from thousand companies in performance in shareholder scoreboard
# Ha: Largest companies donot differ from thousand companies in performance in shareholder scoreboard

observed1 = [108,92,64,84,52]
expected1 = [96,84,80,72,68]


chisquare1 = sum([(x-y)**2/y for x,y in zip(observed1,expected1)])
print('chi_square1: ',chisquare1)

df1 = (5-1)
print('df1: ',df1)

pvalue1 = 1-chi2.cdf(chisquare1, df1)
print('pvalue1: ',pvalue1)

crit = chi2.ppf(1-0.05, df1) #added
print('crit val: ', crit)

chi_square1:  11.226610644257704
df1:  4
pvalue1:  0.0241318738838
crit val:  9.48772903678


In [20]:
# Conclusion: As p-value < .05; Reject Ho. 
# Therefore, Largest companies donot differ from thousand companies in performance in shareholder scoreboard

In [152]:
# 3. Question 9 page 561

In [153]:
# Hypothesis test:

# Ho: Temperature level has no effect on mean yield of the process
# Ha: Temperature level has an effect on mean yield of the process



In [5]:
data = np.array([[44,42,74,42,53,50,45,48,64,60],[55,78,80,86,60,59,62,52,55,62],[54,65,79,69,79,64,59,78,84,38],[44,73,71,60,64,66,41,55,76,50]])
data

array([[44, 42, 74, 42, 53, 50, 45, 48, 64, 60],
       [55, 78, 80, 86, 60, 59, 62, 52, 55, 62],
       [54, 65, 79, 69, 79, 64, 59, 78, 84, 38],
       [44, 73, 71, 60, 64, 66, 41, 55, 76, 50]])

In [6]:
sample_size = [len(x) for x in data]
sample_size

[10, 10, 10, 10]

In [7]:
n = sum(sample_size)
k = len(sample_size)
print (n,k)

40 4


In [8]:
grand_mean = data.mean()
print (grand_mean)

61.0


In [9]:
sample_mean = data.mean(axis = 1)
print(sample_mean)

[ 52.2  64.9  66.9  60. ]


In [10]:
s = data.std(axis = 1,ddof = 1)
print(s)

[ 10.67499675  11.93919781  14.09846327  12.20200348]


In [11]:
zip(sample_size, sample_mean)


In [12]:
SSTR = sum([x*(y-grand_mean)**2 for x,y in zip(sample_size, sample_mean)])
df_tr = k-1
MSTR = SSTR/df_tr
print(SSTR, MSTR)

1284.6 428.2


In [13]:
SSE = sum([(x-1)*(y**2) for x,y in zip(sample_size, s)])
df_e = n-k
MSE = SSE/df_e
print(SSE, MSE)

5437.4 151.038888889


In [14]:
SST = (n-1)*data.std(ddof=1)**2
df_t = n-1
print(SST, SSTR+SSE)

6722.0 6722.0


In [15]:
# ANOVA, f-test
f_stat = MSTR/MSE
crit = f.ppf(.95, dfn = df_tr, dfd = df_e)
p_value = 1 - f.cdf(f_stat, dfn = df_tr, dfd = df_e)
print('critcal value: ',crit)
 
print('\nTreatment:',SSTR,'          ',df_tr,'   ',MSTR,'     ',f_stat,'  ',p_value)
print('Error:  ',' ',SSE,'          ',df_e,'  ',MSE) 
print('Total:  ',' ',SST,' ',df_t)      fghghhuyiuiiullol8ll      g

critcal value:  2.86626555094

Treatment: 1284.6            3     428.2       2.83503144885    0.051748229475
Error:     5437.4            36    151.038888889
Total:     6722.0   39


In [165]:
# Conclusion: As p-value > .05; We do not Reject Ho. 
# Therefore, Temperature level doesnot have an effect on mean yield of the process

In [166]:
# 4.	Problem 31 of Chapter 13, 13th edition, page 581


In [225]:
data = np.array([[[41,43],[52,44],[50,46]],
                 [[49,51],[50,46],[48,44]]])

grand_mean = data.mean()
A_mean = data.mean(axis=(2,1))
B_mean = data.mean(axis=(2,0))

TR_mean = data.mean(axis=2)


In [226]:
data.mean(axis=2)

array([[ 42.,  48.,  48.],
       [ 50.,  48.,  46.]])

In [227]:
data.mean(axis=(2, 1))

array([ 46.,  48.])

In [228]:
data.mean(axis=(2, 0))

array([ 46.,  48.,  47.])

In [229]:
SST = sum([(x-grand_mean)**2 for x in data.flatten()])

data.flatten()

array([41, 43, 52, 44, 50, 46, 49, 51, 50, 46, 48, 44])

In [230]:
# shape of the numpy array

data.shape

(2, 3, 2)

In [231]:
a = data.shape[0]; b = data.shape[1]; r = data.shape[2]

In [232]:
SSA = b*r*sum([(x-grand_mean)**2 for x in A_mean])

In [233]:
SSB = a*r*sum([(x-grand_mean)**2 for x in B_mean])

In [234]:
# compute SSAB

SSAB = 0
for i in range(a):
    for j in range(b):
        SSAB += (TR_mean[i][j] - A_mean[i] - B_mean[j] + grand_mean)**2
SSAB = r*SSAB

In [235]:
# Compute SSE

SSE = SST - SSA - SSB - SSAB

In [236]:
# degrees of freedom

dfa = data.shape[0] - 1
dfb = data.shape[1] - 1
dfab = dfa * dfb
dfe = data.shape[0] * data.shape[1] * (data.shape[2] - 1)
dft = data.shape[0] * data.shape[1] * data.shape[2] - 1

In [237]:
# Mean Squares

MSA = SSA/dfa
MSB = SSB/dfb
MSAB = SSAB/dfab
MSE = SSE/dfe

In [238]:
# F test statistics

fa = MSA/MSE
fb = MSB/MSE
fab = MSAB/MSE

In [239]:
# P VALUES

pa = 1 - f.cdf(fa, dfn = dfa, dfd = dfe)
pb = 1 - f.cdf(fb, dfn = dfb, dfd = dfe)
pab = 1 - f.cdf(fab, dfn = dfab, dfd = dfe)

In [248]:
print('Factor A','      ', SSA,'  ',dfa,'   ',MSA,'   ',fa,'    ',pa)
print('Factor B','      ', SSB,'   ',dfb,'   ',MSB,'    ',fb,'    ',pb)
print('Interaction','   ', SSAB,'  ',dfab,'   ',MSAB,'   ',fab,'    ',pab)
print('Error','         ', SSE,'  ',dfe,'   ',MSE)
print('Total','         ', SST,' ',dft)

Factor A        12.0    1     12.0     1.2      0.315333596201
Factor B        8.0     2     4.0      0.4      0.686952981885
Interaction     56.0    2     28.0     2.8      0.138382057485
Error           60.0    6     10.0
Total           136.0   11


In [ ]:
# Conclusion:

# With p-value for Factor-A  (0.315333596201) greater than .05, it is not significant
# With p-value for Factor-B  (0.686952981885) greater than .05, it is not significant
# With p-value for Interaction of A and B  ( 0.138382057485) greater than .05, 
# therefore, it is not significant for decreasing wait times

#As method is not a significant factor; either of the methods; Loading and Unloading can be used

In [3]:
# just checking
ch = chi2.ppf(1-.05,2)
ch

5.9914645471079799